#!/data/data/com.termux/files/usr/bin/bash
# YouTube Downloader Configuration

# mp4 single video

# mp4 specific configs: {{{ 1

# Filetype
-f mp4

# Filenames
--restrict-filenames

# Output location
-o "$HOME/storage/shared/Videos/%(creator)s/%(title)s.%(ext)s"

# Metadata
--add-metadata
--metadata-from-title "%(artist)s - %(title)s"

# Modification time
--no-mtime

# Subtitles
# Write autosubs only works with YT and videos
--write-auto-sub
--embed-subs

# Thumbnails
--embed-thumbnail

# Don't phone home
--no-call-home

# Don't use proprietary encodings
--youtube-skip-dash-manifest

# }}}
