#!/bin/bash
# YouTube Downloader Configuration
# Maintainer: Faris Chugthai

# Possibly better to save mutiple configs then change which one we use
# Based on the situation using `--config-location`
# Be aware you can use `--no-config

# mp3

# Filetype
-f mp3

# Filenames
--restrict-filenames

# Output location
-o "$HOME/storage/shared/Videos/%(title)s.%(ext)s"

# Metadata
--add-metadata 
--metadata-from-title "%(artist)s - %(title)s"

# Filetype
-x --audio-format mp3 --audio-quality 0 --prefer-ffmpeg 

# Modification Time
--no-mtime

# Thumbnails
--embed-thumbnail

# Modification time
--no-mtime 

# Subtitles
--write-auto-sub
--embed-subs 

# Thumbnails
--embed-thumbnail 

# Don't phone home
--no-call-home 

# Don't use proprietary encodings
--youtube-skip-dash-manifest


# Testing

#-o "$HOME/storage/shared/Music/%(artist)s/%(album)s/%(title)s.%(ext)s" 
