#!/data/data/com.termux/files/usr/bin/bash
# YouTube Downloader Configuration
# Maintainer: Faris Chugthai

# mp4 single video

# Filetype
-f mp4

# Filenames
--restrict-filenames

# Metadata
--add-metadata
# --metadata-from-title "%(artist)s - %(title)s"
--metadata-from-title "(?P<artist>.+?) - (?P<title>.+)"

# Output location
-o "$HOME/storage/shared/Videos/%(artist)s/%(title)s.%(ext)s"

# Modification time
--no-mtime

# Thumbnails
# --embed-thumbnail

# Don't phone home
--no-call-home

# Don't use proprietary encodings
--youtube-skip-dash-manifest

# User Agent
# --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0 (Chrome)"
