#!/data/data/com.termux/files/usr/bin/bash
# youtube-dl

# mp4-playlist: {{{ 1

# mp4 specific configs: {{{ 2

# Filetype
-f mp4

# Filenames
--restrict-filenames

# Output location
# TODO: Doesn't wirk
-o "$HOME/storage/shared/Videos/%(uploader)s/%(title)s.%(ext)s"

# TODO:Add in a UA
# --user-agent UA
# Also implement this!
# --exec CMD
# Execute a command on the file after downloading, similar to
# find's -exec syntax.  Example: --exec 'adb push {} /sdcard/Music/ && rm {}'

# Metadata
--add-metadata
--metadata-from-title "%(artist)s - %(title)s"

# Modification time
--no-mtime

# Subtitles
# Write autosubs only works with YT and videos
--write-auto-sub
--embed-subs

# Thumbnails
--embed-thumbnail

# Don't phone home
--no-call-home

# Don't use proprietary encodings
--youtube-skip-dash-manifest

# }}}

# Playlist specific: {{{ 2

# playlist. simple as that. output template updated to reflect playlist pos
--yes-playlist

# download archive. if the script is rerun on the same playlist only download
# new videos
--download-archive "$HOME/storage/shared/Videos/%(creator)s/%(playlist_index)d%(title)s.%(ext)s"

# }}}

# }}}
