# BYOBU_DARK="\#4c169c"
# BYOBU_LIGHT=black
# BYOBU_ACCENT=magenta
# BYOBU_HIGHLIGHT=red
BYOBU_HIGHLIGHT=#282828
MONOCHROME=
BYOBU_DARK='#1d2021'
BYOBU_LIGHT='#ebdbb2'
BYOBU_ACCENT='#fe8019'

# Vim: set ft=tmux:
