#!/data/data/com.termux/files/usr/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# If there are whitespace errors, print the offending file names and fail.

# exec git diff-index --check --cached $against --

# exit 0
